const playersData = [
  {
    id: 1,
    name: "Timmy",
    avatar: "/avatar.png",
    position: "Forward",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Kubi",
    avatar: "/avatar.png",
    position: "Midfielder",
    rating: 4.1,
  },
  {
    id: 3,
    name: "Eren",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 4,
    name: "Env",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 5,
    name: "Big Dogan",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 6,
    name: "Ali",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 7,
    name: "Mem",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 8,
    name: "Ibo",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 9,
    name: "Beha",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 10,
    name: "Ahmed",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 11,
    name: "Simon",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 12,
    name: "Ashley",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 13,
    name: "Jordan",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  {
    id: 14,
    name: "Drew",
    avatar: "/avatar.png",
    position: "Defender",
    rating: 3.8,
  },
  // Add more players here
];

export default playersData;
