const playersData = [
  {
    id: 1,
    name: "Timmy",
    avatar: "/avatar.png",
    position: "Forward",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Kubi",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 4.1,
  },
  {
    id: 3,
    name: "Eren",
    avatar: "/avatar.png",
    position: "Waffler",
    rating: 3.5,
  },
  {
    id: 4,
    name: "Env",
    avatar: "/avatar.png",
    position: "Keeper",
    rating: 4.0,
  },
  {
    id: 5,
    name: "Big Dogan",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 4.1,
  },
  {
    id: 6,
    name: "Ali",
    avatar: "/avatar.png",
    position: "Top Waffle",
    rating: 3.8,
  },
  {
    id: 7,
    name: "Mem",
    avatar: "/avatar.png",
    position: "Wing",
    rating: 4.1,
  },
  {
    id: 8,
    name: "Ibo",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 3.9,
  },
  {
    id: 9,
    name: "Beha",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 4.3,
  },
  {
    id: 10,
    name: "Ahmed",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 4.2,
  },
  {
    id: 11,
    name: "Simon",
    avatar: "/avatar.png",
    position: "Keeper",
    rating: 4.1,
  },
  {
    id: 12,
    name: "Ashley",
    avatar: "/avatar.png",
    position: "All over",
    rating: 3.8,
  },
  {
    id: 13,
    name: "Jordan",
    avatar: "/avatar.png",
    position: "When he turns up",
    rating: 3.8,
  },
  {
    id: 14,
    name: "Drew",
    avatar: "/avatar.png",
    position: "Yaminations",
    rating: 3.8,
  },
  {
    id: 15,
    name: "Tuggs",
    avatar: "/avatar.png",
    position: "Scrapper",
    rating: 4.0,
  },
  {
    id: 16,
    name: "Brogan",
    avatar: "/avatar.png",
    position: "#bants",
    rating: 4.3,
  },
  {
    id: 17,
    name: "Kevin",
    avatar: "/avatar.png",
    position: "Photographer",
    rating: 4.0,
  },
  {
    id: 18,
    name: "PJ",
    avatar: "/avatar.png",
    position: "Midfielder",
    rating: 4.0,
  },
  {
    id: 19,
    name: "Sat",
    avatar: "/avatar.png",
    position: "Piss Head",
    rating: 3.9,
  },
  {
    id: 20,
    name: "Stuart",
    avatar: "/avatar.png",
    position: "Wing",
    rating: 3.8,
  },
  {
    id: 21,
    name: "Ashley",
    avatar: "/avatar.png",
    position: "Midfielder",
    rating: 3.8,
  },
  {
    id: 22,
    name: "Alastair",
    avatar: "/avatar.png",
    position: "Striker",
    rating: 4.0,
  },

  // Add more players here
];

export default playersData;
